# Python Data Analysis | 👋🏼 ⭐️⭐️⭐️⭐️⭐️ 👾
Treehouse Live with Jonathan Barrios: Python Data Analysis with Jupyter Notebook, Pandas, Numpy, Matplotlib, and Seaborn from the very beginning 🌐 Sign-up [for notifications](https://join.teamtreehouse.com/treehouse-live/) 🍿


# 🐍 PART I | [YouTube Livestream](https://www.youtube.com/watch?v=1bfXUwcs-OU) 5.22.2020


## Import data analysis libraries pandas and numpy

In [1]:
# import pandas as pd
import pandas as pd
# import numpy as np
import numpy as np

### Create some test data
##### Let's use [numpy.random.randint](https://numpy.org/doc/1.18/reference/random/generated/numpy.random.randint.html?highlight=randint#numpy.random.randint) for this

In [2]:
# Use numpy to generate 25 random integers between 1-100
test_data = np.random.randint(1,100,100)

### Return that data

In [3]:
# Return data
test_data

array([79, 73, 81, 75, 81, 86, 50, 15, 38, 20, 17, 57, 21, 23, 90, 58, 15,
       19,  3, 42,  6, 96, 37, 27, 52, 79, 61, 34,  8,  7, 19, 44, 80, 39,
       35, 21, 86, 75, 38, 81, 86, 34, 19, 55, 56, 61,  8, 37, 79, 67, 84,
       11, 82, 56,  7, 81, 51, 49, 75, 23, 62, 38,  8, 31, 54, 40, 65, 52,
       31, 76, 26, 88, 10, 35, 97, 78, 81, 41, 67,  5, 26, 80, 73, 57, 93,
       60, 89, 49, 26, 38, 68, 27, 98, 21, 53, 27, 29, 50, 50, 45])

## Create star ratings test data ⭐️⭐️⭐️⭐️⭐️
##### Let's use [numpy.linspace](https://numpy.org/devdocs/reference/generated/numpy.linspace.html) for this

In [4]:
# Create random floats wich are evenly spaced between 1 and 5
data = np.linspace(1,5,25)

### Return that data

In [24]:
# Return data
data

array([1. , 1.2, 1.3, 1.5, 1.7, 1.8, 2. , 2.2, 2.3, 2.5, 2.7, 2.8, 3. ,
       3.2, 3.3, 3.5, 3.7, 3.8, 4. , 4.2, 4.3, 4.5, 4.7, 4.8, 5. ])

### Wrangle that data

In [27]:
# Round the number with one decimal integer
data = np.around(np.linspace(1,5,25),1)

### Return that data

In [28]:
# Return data
data

array([1. , 1.2, 1.3, 1.5, 1.7, 1.8, 2. , 2.2, 2.3, 2.5, 2.7, 2.8, 3. ,
       3.2, 3.3, 3.5, 3.7, 3.8, 4. , 4.2, 4.3, 4.5, 4.7, 4.8, 5. ])

# What is Pandas?
Pandas is data analysis tool built on top of Python.

# What is a Pandas Series?
A Pandas Series is a one-dimensional labeled array that holds any data type (integer, string, float, python objects, etc.). In short, a Pandas Series is nothing but a **column** in an excel sheet. Let's make one!

In [11]:
# Make Pandas Series
series = pd.Series(data)

### Return Pandas  Series

In [12]:
# Return Sesries
series

0     1.0
1     1.2
2     1.3
3     1.5
4     1.7
5     1.8
6     2.0
7     2.2
8     2.3
9     2.5
10    2.7
11    2.8
12    3.0
13    3.2
14    3.3
15    3.5
16    3.7
17    3.8
18    4.0
19    4.2
20    4.3
21    4.5
22    4.7
23    4.8
24    5.0
dtype: float64

### Return an index that starts at 1 instead of 0

In [13]:
# Set index to 1
series.index = series.index + 1 
# return series
series

1     1.0
2     1.2
3     1.3
4     1.5
5     1.7
6     1.8
7     2.0
8     2.2
9     2.3
10    2.5
11    2.7
12    2.8
13    3.0
14    3.2
15    3.3
16    3.5
17    3.7
18    3.8
19    4.0
20    4.2
21    4.3
22    4.5
23    4.7
24    4.8
25    5.0
dtype: float64

### Series mean
The mean is the average of the numbers which is easy to calculate: add up all the numbers, then divide by how many numbers there are. In other words it is the sum divided by the count but with Pandas, all we need to do is use the mean() function.

In [15]:
# Return series.mean()
series.mean()

3.0

### Series by Index

In [16]:
# return series[by_index]
series[13]

3.0

### Are Series are one dimensional?

In [17]:
# Return series.shape
series.shape

(25,)

# What is a DataFrame?
The long answer is a two-dimensional size-mutable, potentially heterogeneous tabular data structure with labeled axes. The short answer is, **rows and columns**.

### Pandas Data Frames are two dimensional(rows & columns)

In [18]:
# Create a two dimensional data frame
df = pd.DataFrame(data, columns=['ratings'])

### Return two dimensional data frame

In [19]:
# Return two dimensional data frame
df

ratings
0       1.0
1       1.2
2       1.3
3       1.5
4       1.7
5       1.8
6       2.0
7       2.2
8       2.3
9       2.5
10      2.7
11      2.8
12      3.0
13      3.2
14      3.3
15      3.5
16      3.7
17      3.8
18      4.0
19      4.2
20      4.3
21      4.5
22      4.7
23      4.8
24      5.0

### Set index to start at index 1

In [20]:
# Set index to 1
df.index = df.index + 1

### Return the two dimensional data frame starting at index 1

In [21]:
df

ratings
1       1.0
2       1.2
3       1.3
4       1.5
5       1.7
6       1.8
7       2.0
8       2.2
9       2.3
10      2.5
11      2.7
12      2.8
13      3.0
14      3.2
15      3.3
16      3.5
17      3.7
18      3.8
19      4.0
20      4.2
21      4.3
22      4.5
23      4.7
24      4.8
25      5.0

# 🐍 PART II | [YouTube Livestream](https://www.youtube.com/watch?v=QDxZy-docoU) 5.29.2020


### Check the type for a DataFrame?

In [29]:
# return type()
type(df)

pandas.core.frame.DataFrame

### Extract DataFrame rows using [iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html) with indices 2, 3, and 8.

- [iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html) -- Selecting data by row numbers (.iloc)

- [loc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) -- Selecting data by label or by a conditional statment (.loc)

In [30]:
# extract data using iloc indices 2,3 and 8
mini_data_frame = df.iloc[[2,3,8]]

### Return new data frame 

In [31]:
# return new data frame
mini_data_frame

ratings
3      1.3
4      1.5
9      2.3

### Extract DataFrame rows using the index syntax :6

In [32]:
# return new data frame using the index :6 syntax
mini_data_frame = df.iloc[:6]

### Return new data frame displaying result using :6 

In [33]:
# return new data frame displaying result using :6 
mini_data_frame

ratings
1      1.0
2      1.2
3      1.3
4      1.5
5      1.7
6      1.8



# Review: Series vs DataFrames
Series have one column while data frames have rows and columns. Let's compare them below:

In [34]:
# check type() for mini_data_frame
type(mini_data_frame)

pandas.core.frame.DataFrame

In [38]:
# check type() for mini_series = df.iloc[2]
mini_series = df.iloc[2]
type(mini_series)

pandas.core.series.Series

## Mean, median, describe and more...
- [mean()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.mean.html)
- [median()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.median.html?highlight=dataframe%20median#pandas.DataFrame.median)
- [describe()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.describe.html?highlight=dataframe%20describe#pandas.DataFrame.describe)
- [max()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.max.html#pandas.DataFrame.max)
- [min()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.max.html#pandas.DataFrame.min)

In [39]:
# return mean()
df.mean()

ratings    3.0
dtype: float64

In [41]:
# return median()
df.median()

ratings    3.0
dtype: float64

In [42]:
# return describe()
df.describe()

ratings
count  25.000000
mean    3.000000
std     1.225425
min     1.000000
25%     2.000000
50%     3.000000
75%     4.000000
max     5.000000

# Remember this test data we generated with Numpy?

In [43]:
# earlier test data
test_data = np.random.randint(1,100,25)
# return that data
test_data

array([20,  3, 81, 31, 36, 67, 36, 79, 19, 74, 92, 59, 19, 24, 37, 96, 69,
       23, 29, 11,  6, 77, 41, 53, 36])

### How about multidemensional array?

In [44]:
# reshape() test data with a 5 x 5 multidimensional array
test_data = np.random.randint(1,80,25).reshape(5,5)
# return that data
test_data

array([[ 1, 66, 10, 12, 57],
       [71, 11, 67, 29, 46],
       [18, 40, 20, 66, 10],
       [19, 71, 20, 23, 35],
       [77, 42, 60, 16, 22]])

# 🐍 PART III | 6.05.2020

### What's the shape() of this array?

In [3]:
# return shape() of test_data


### Convert the test_data into a test_data_frame

In [51]:
# return test_data_frame


### add descriptive column names

In [52]:
# add descriptive column names


In [53]:
# return test_data_frame as df


### add descriptive index names

In [54]:
# add descriptive index names


In [55]:
# return test_data_frame as df


### What's the 411? or info()?

In [ ]:
# return info()


### Perform math operations on columns saved as 'Total'

In [ ]:
# add the sum of each rows to a new column, 'Total'


### Return new DataFrame

In [ ]:
# return new data frame


### Perform boolean operations on columns saved as 'Profit'

In [59]:
# check each row for boolean condition of > 200 to a new column, 'Profit'


### Return new DataFrame

In [ ]:
# return new data frame


### Drop the 'Profit' column
Use the optinal parameters: axis=0 for index, and axis=1 for columns (default =0)

Read more on [DataFrame.drop()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html?highlight=dataframe%20drop#pandas.DataFrame.drop)

In [57]:
# drop the 'Profit' column (using the correct axis=*)


### Return new DataFrame without the 'Profit' column

In [ ]:
# return new data frame


# Matplotlib and Seaborn

### Import pyplot from matplotlib as plt
### Import seaborn as sns

In [56]:
# import pyplot from matplotlib as plt

# import seaborn as sns


### Create a plot using pyplot as plt

In [60]:
# Create a plot with pyplot as plt using new_df and the 'Total' column
